title: Mike Rich # your name (or website title) here
logo: "/images/me.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <a href="https://www.linkedin.com/in/michaelrich01/">LinkedIn</a> 
  <br>  
  <a href="/pdf/Michael_Rich_Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/mikebrich/">GitHub</a>  
  <br>

  
theme: jekyll-theme-minimal
